# SPDX-FileCopyrightText: 2025 Swiss Confederation
#
# SPDX-License-Identifier: MIT
#

services:
  postgres:
    image: postgres:15.8
    hostname: localhost
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "secret"
      POSTGRES_DB: "trust-registry-db"
    ports:
      - '5380:5432'
    volumes:
      - trust_registry_auth_db_data:/var/lib/postgresql/data

volumes:
  trust_registry_auth_db_data:
